clear all
close all
clc

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/jean-philippe/Documents/COVID_19/COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv
%
% Auto-generated by MATLAB on 06-Mar-2020 01:51:41

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 48);

% Specify range and delimiter
opts.DataLines = [2, 173];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Lat", "Long", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43", "VarName44", "VarName45", "VarName46", "VarName47", "VarName48"];
opts.SelectedVariableNames = ["Lat", "Long", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43", "VarName44", "VarName45", "VarName46", "VarName47", "VarName48"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2"], "EmptyFieldRule", "auto");

% Import the data
timeseries19covidConfirmed = readtable("/home/jean-philippe/Documents/COVID_19/COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv", opts);

%% Convert to output type
T = table2array(timeseries19covidConfirmed);

%% Clear temporary variables
clear opts

%% Data analysis
% Tx = T(:,1);
% Ty = T(:,2);
% dLat = diff(sort(Tx));
% dLon = diff(sort(Ty));
% [mLat,i] = min(nonzeros(dLat'));
% [mLon,j] = min(nonzeros(dLon'));
% disp(["min lat = " mLat]);
% disp(["min lon = " mLon]);

[X, Y] = meshgrid(-180:1:180, -90:1:90);
Z = zeros(size(X));
for j = 2:length(T(:,1))
    Z(90  + round(T(j,1)), ...
      180 + round(T(j,2))) = ...
    Z(90  + round(T(j,1)), ...
      180 + round(T(j,2)))  +...
    round(T(j,end));
end

figure()
surf(X,Y,Z)
zlim([0,100])


for i = 3:length(T(1,:))
    for j = 2:length(T(:,1))
        Z(90  + round(T(j,1)), ...
          180 + round(T(j,2))) = ...
        Z(90  + round(T(j,1)), ...
          180 + round(T(j,2)))  +...
        round(T(j,end));
    end
    vec = [reshape(X,[],1),reshape(Y,[],1),reshape(Z,[],1)];
    filename = ['data' num2str(i-2) '.mat'];
    save(filename,'vec')
end
